# Generated by Django 5.2 on 2025-05-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muongxen',
            name='st_cua_dat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='muongxen',
            name='st_muong_la',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='muongxen',
            name='st_muong_xen',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='muongxen',
            name='st_quy_chau',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='muongxen',
            name='st_xa_la',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='muongxen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
