# Generated by Django 5.2 on 2025-05-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_muongxen_st_cua_dat_muongxen_st_muong_la_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muongxen',
            name='st_cua_dat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='muongxen',
            name='st_muong_la',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='muongxen',
            name='st_muong_xen',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='muongxen',
            name='st_quy_chau',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='muongxen',
            name='st_xa_la',
            field=models.IntegerField(null=True),
        ),
    ]
