# Generated by Django 5.2 on 2025-05-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_muongxen_st_cua_dat_alter_muongxen_st_muong_la_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muongxen',
            old_name='st_muong_la',
            new_name='st_muong_lat',
        ),
    ]
