# Generated by Django 4.2.21 on 2025-06-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_st_muong_la_muongxen_st_muong_lat'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField()),
                ('password', models.CharField()),
            ],
        ),
    ]
